const $ = (s) => document.querySelector(s);
const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const statusText = {healthy:'정상', degraded:'주의', down:'장애', unknown:'확인 필요', planned:'구축 예정'};
const statusClass = (s) => ({healthy:'ok', degraded:'warn', down:'down', unknown:'unknown', planned:'planned'}[s] || 'unknown');
let services = [];
function fmtDate(value) { if (!value) return '기록 없음'; const d = new Date(value); return Number.isNaN(d.getTime()) ? value : d.toLocaleString('ko-KR', {dateStyle:'medium', timeStyle:'short'}); }
function checkSummary(service) { const checks = service.checks || []; if (!checks.length) return '자동 점검 없음'; return checks.map(c => `${esc(c.name)}: ${esc(statusText[c.status] || c.status)}`).join(' · '); }
function renderSummary() { const operating = services.filter(s => s.lifecycle === 'operating'); const healthy = operating.filter(s => s.automated_status === 'healthy').length; const attention = services.filter(s => ['down','degraded','unknown'].includes(s.automated_status)).length; $('#summary').innerHTML = `<div class="stat"><small>운영 서비스</small><b>${operating.length}</b><span>${healthy}/${operating.length} 정상</span></div><div class="stat"><small>확인 필요</small><b class="${attention ? 'warn' : 'ok'}">${attention}</b><span>자동 상태 기준</span></div><div class="stat"><small>예정 서비스</small><b>${services.filter(s => s.lifecycle === 'planned').length}</b><span>범위 결정 대기</span></div><div class="stat"><small>데이터 원본</small><b>VPS + GitHub</b><span>읽기 전용 수집</span></div>`; }
function renderCards(filter='all') { let visible = services.filter(s => filter === 'all' || (filter === 'attention' ? ['down','degraded','unknown'].includes(s.automated_status) : s.lifecycle === filter)); $('#service-count').textContent = `${visible.length}개 표시`; $('#services').innerHTML = visible.map(s => `<article class="card"><div class="card-head"><div><span class="service-name">${esc(s.name)}</span><p>${esc(s.description)}</p></div><span class="pill ${statusClass(s.automated_status)}">● ${esc(statusText[s.automated_status] || s.automated_status)}</span></div><div class="meta"><div><small>점검</small><span>${checkSummary(s)}</span></div><div><small>최근 GitHub</small><span>${esc(s.github?.latest_commit?.message || '기록 없음')}</span></div></div><div class="card-foot"><span>다음: ${esc(s.next_action || '미정')}</span>${s.public_url ? `<a href="${esc(s.public_url)}" target="_blank" rel="noreferrer">서비스 ↗</a>` : ''}</div></article>`).join('') || '<div class="empty">해당 조건의 서비스가 없습니다.</div>'; }
function renderLists() { const updates = services.filter(s => s.github?.latest_commit).sort((a,b) => String(b.github.latest_commit.date).localeCompare(String(a.github.latest_commit.date))); $('#updates').innerHTML = updates.map(s => `<div class="list-item"><b>${esc(s.name)}</b><span>${esc(s.github.latest_commit.message)}</span><small>${fmtDate(s.github.latest_commit.date)}</small></div>`).join('') || '<div class="empty">업데이트 기록 없음</div>'; $('#next-actions').innerHTML = services.map(s => `<div class="list-item"><b>${esc(s.name)}</b><span>${esc(s.next_action || '미정')}</span></div>`).join(''); $('#attention').innerHTML = services.filter(s => ['down','degraded','unknown'].includes(s.automated_status)).map(s => `<div class="list-item"><b>${esc(s.name)}</b><span>${esc(statusText[s.automated_status])}: ${checkSummary(s)}</span></div>`).join('') || '<div class="healthy">● 현재 자동 확인 항목 없음</div>'; }
async function start() { try { const response = await fetch('snapshot.json', {cache:'no-store'}); if (!response.ok) throw new Error(`snapshot ${response.status}`); const data = await response.json(); services = data.services || []; $('#collected').textContent = `마지막 수집 ${fmtDate(data.collected_at)}`; renderSummary(); renderCards(); renderLists(); document.querySelectorAll('.filter').forEach(b => b.addEventListener('click', () => { document.querySelectorAll('.filter').forEach(x => x.classList.remove('active')); b.classList.add('active'); renderCards(b.dataset.filter); })); } catch (error) { $('#collected').textContent = '수집 결과 없음'; $('#services').innerHTML = `<div class="error">운영 상태를 불러오지 못했습니다. 수집기 로그를 확인해 주세요.</div>`; console.error(error); } }
start();
